filter_test.go, filterparser.go, filterparser_test.go, filters.go, filters_test.go, filterscanner.go
This patch moves the `manipulate.Filter` to elemental.
This patch is required to allow a deeper understanding of filters, so libraries that are not necessarily using manipulate can use filtering.
The end goal of this move is to allow 
- checking is an `elemental.Identifiable` matches a filter
- extracting matching `elemental.Identifiable` from a `elemental.Identifiables` list
- advanced push filtering
=> new: move manipulate.FIlter in elemental

.gitignore, encoding.go, encoding_test.go
https://github.com/aporeto-inc/elemental/blob/master/encoding.go#L144
An interface will only be `nil`, *if and only if*, both it's type and value are nil. If the caller of `Encode` passes in a `nil` pointer here, this condition would not trigger because the interface is not actually nil anymore as it now has a type set (i.e. `*T`) even though it's value is `nil`!
https://play.golang.org/p/E1tlCOb32P
I ran into this by passing a `nil` `Publication` to cause a deliberate encoding error in my unit test, but to my surprise this did not trigger this short circuit.
Example of a caller that can pass in a `nil` pointer type - https://github.com/aporeto-inc/bahamut/blob/master/pubsub_nats.go#L69
---
If this patch is accepted, please create a new tag `v1.47.0` 🙏
=> encode: fix nil check

atomicjob.go, atomicjob_test.go
This patch adds the function AtomicJob that
allows to make a function execution atomic
while still returning any eventual error to every callers.
=> new: added AtomicJob

matcher.go, matcher_test.go
----
This PR builds on the new API ([`MatchesFilter`](https://github.com/aporeto-inc/elemental/blob/0dd2cd80284899e24d0d7ed97a15c30683b3a8eb/matcher.go#L9)) introduced in https://github.com/aporeto-inc/elemental/pull/56 by adding support for filtering w/ the `MatchComparator` comparator.
**Example usage**
```go
auto := gaia.NewAutomation()
auto.NormalizedTags = []string{
"$identity=automation",
"$name=Test Automation",
"$namespace=/account-9bb41b0a-8703-40ca-b3e6-975d727fcba7",
"$id=5d5208a1339d6456750010b5",
}
matched, err := elemental.MatchesFilter(auto,
elemental.NewFilterComposer().
WithKey("normalizedTags").
Matches(
// valid pattern, but won't match anything
"nomatch",
// invalid pattern, won't compile to a regex
"*",
// invalid pattern, MUST be a string
1234,
// valid pattern, will …
```
=> new: add support for the 'MatchComparator' comparator to MatchesFilter

matcher.go, matcher_errors.go, matcher_test.go
This PR adds a custom error type that will be returned as the error value whenever `MatchesFilter` returns an error. Client's can then use this type in their error handling strategy to properly deal with errors returned by this API.
The first client that will take advantage of this is one of Aporeto's backend services (_which is a bahamut push server_) that needs to deduce whether `MatchesFilter`  is returning an error due to the client using an unsupported filter comparator. In the event that this is the case, it will return back with some error type from it's `ShouldDispatch` callback that will indicate to bahamut that it should close the socket! That part will be added as a part of [this PR](https://github.com/aporeto-inc/bahamut/pull/82).
- See the test cases to get an idea on how …
=> Add custom error type for errors returned by the 'MatchesFilter' API 

push_config.go, push_config_test.go, push_filter.go, push_filter_test.go
TODOs
- This needs a new API
- This needs a new set of unit tests
=> Add support for fine-grained identity filtering on websockets

filterparser.go, filterparser_options.go, filterparser_test.go
Resolves: https://github.com/aporeto-inc/aporeto/issues/2495
This PR adds support to the filter parser to accept a blacklist of comparators via a new functional option - `OptUnsupportedComparators`.
=> new: add support to filter parser for blacklisting filter comparators 

cmd/elegen/utils.go
What happened is upstream added a new rule to gosec to make it yell when we ignore errors from function calls https://github.com/securego/gosec/commit/7525fe4bb7b0b8b5c81d6eb011d6fdf8300ea420
this new rule subsequently caught a violation with:
```
[/home/travis/gopath/src/github.com/aporeto-inc/elemental/cmd/elegen/utils.go:51] - G307 (CWE-): Deferring unsafe method "*os.File" on type "Close" (Confidence: HIGH, Severity: MEDIUM)
> defer f.Close()
```
=> edit: fix gosec false positive

.travis.yml, cmd/elegen/utils.go, matcher.go, matcher_test.go
@ayliao raised an issue where his filter was failing to find a match on an alarm's [`status` attribute](https://github.com/aporeto-inc/gaia/blob/2cc82a4bb719a3cbbfaeb2182b5729464436257f/alarm.go#L151). This was happening because the value provided to the comparator (a string) did not have the same type as the target attribute (`AlarmStatusValue`).
To address this in a general way, we try to convert the type of the value passed into the comparator to that of the attribute's type being filtered on.
=> fix: (try to) convert the type of the `Equals` comparator's value to attribute type

encoding.go, encoding_test.go, request.go, request_test.go
Do not read the body or try to decode the data when content-type or accept header is set to be one of the registered custom mime type.
This means the Data property of elemental.Request will not be populated. The handler must deal with reading the body from the internal http.Request.
=> new:  better support for custom mime-types

encoding.go, encoding_test.go
This patch adds the two following functions for encoding
- `func MakeStreamDecoder(encoding EncodingType, reader io.Reader) (func(dest interface{}) error, func())`
- `func MakeStreamEncoder(encoding EncodingType, writer io.Writer) (func(obj interface{}) error, func())`
Both of them return a function to perform a single encode/decode operation that can be called in a loop until `io.EOF` and a second function used to abort and put the data back in the shared memory pools.
> NOTE: there is a bug in the codec library making the JSON version unable to to retun io.EOF. See https://github.com/ugorji/go/issues/334
=> new: added MakeStreamEncoder and MakeStreamDecoder

request.go, request_test.go
As per https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For, X-Forwarded-For needs to be parsed to extract the client IP.
=> fix/request: Use first part of X-Forwarded-For as client IP.

parameters.go, parameters_test.go
The logic to validate parameter requirements was flawed after introducing multiple requirement blocks.
=> fixed: parameter requirements validation logic

cmd/elegen/writers.go
This patch adds a validation to ensure unicity of bson_name is a spec.
=> new/elegen: complain when a bson name is reused

encoding_test.go, filterparser.go, go.mod, go.sum
Through a lengthy debug session, we had encountered an infinite loop issue within the go codec that we use in elemental. The following issue tracks both the fix and the related tickets: https://github.com/ugorji/go/pull/320
Added is the bump to latest codec and a unit test to cover the offending character.
=> Fixed: Bump go codec to handle special char encoding and added unit test

attribute.go, attribute_test.go
this patch fixes a panic when various nil values were passed to ResetSecretAttributesValues.
=> fixed: fix panic on nil input in ResetSecretAttributesValues

cmd/internal/genopenapi3/converter_relations_model_nonroot_test.go, cmd/internal/genopenapi3/converter_relations_spec_nonroot_test.go, cmd/internal/genopenapi3/converter_relations_spec_root_test.go, cmd/internal/genopenapi3/gen_converter.go, cmd/internal/genopenapi3/gen_relations.go
This PR ensures that fields `tags` and `operationId` are populated in the output OpenAPI3 doc:
eg:
```
"/accessiblenamespaces": {
"get":{
"operationId": "get-all-accessiblenamespaces",
"tags": ["core/accessiblenamespace", "squall"],
...
```
This is done for all operations, ie GET/POST/PUT/DELETE
=> Enahncement/openapi3: include tags + operationID

utils.go, utils_test.go
Previously, IsZero() was panicking when the given object
was a nil pointer. This patch makes IsZero() leverage reflect's
value.IsZero() to simplify the code.
=> fixed: IsZero when using a nil pointer prop

go.mod, go.sum
There is a worthwhile fix in the go codec release of v1.2.7 that came out 2 days ago: https://github.com/ugorji/go/releases/tag/v1.2.7
We should try to bring this into elemental if able.
=> Update: Bump go codec to v1.2.7

cmd/internal/genopenapi3/converter_model_nonroot_test.go, cmd/internal/genopenapi3/converter_relations_spec_root_test.go, cmd/internal/genopenapi3/converter_split_output_test.go, cmd/internal/genopenapi3/gen_converter.go, cmd/internal/genopenapi3/gen_relations.go
This PR ensures that not only we avoid converting schemas for private models, but also that we ignore converting tags and root relations that belong to private models ONLY and only if --public flag is passed
=> Bugfix: completely ignore private models if public flag is passed

cmd/elegen/utils.go, cmd/elegen/writers.go
While switching to cases library, we need to make sure to apply `cases.NoLower` to keep the same behavior as before.
=> Fixed: Add NoLower to keep with old behavior

cmd/internal/genopenapi3/converter_errors_test.go, cmd/internal/genopenapi3/converter_helpers_test.go
This pull request replaces `os.MkdirTemp` with `t.TempDir`. We can use the `t.TempDir` function from the `testing` package to create temporary directory. The directory created by `t.TempDir` is automatically removed when the test and all its subtests complete. 
This saves us at least 2 lines (error check, and cleanup) on every instance.
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := os.MkdirTemp("", "")
if err != nil {
t.Fatal(e)
}
defer os.RemoveAll(tmpDir)
// now
tmpDir := t.TempDir()
}
```
=> test: use `t.TempDir` to create temporary test directory

Makefile, filters.go, filters_test.go
This PR fixes the following bug:
Given the following filter:
```
f := elemental.NewFilter().WithKey("name").NotIn("abc001", "abc002").Done()
```
The `f.String()` representation only shows the first element:
```
(name not in "abc001")
```
The correct, expected representation is:
```
(name not in ["abc001", "abc002"])
```
Which is analogous to the behaviour of the `In` comparator:
```
f := elemental.NewFilter().WithKey("name").In("abc001", "abc002").Done()
``` 
which returns the following `f.String()` representation:
```
(name in ["abc001", "abc002"])
```
=> Fixed: string representation for "not in" filter comparator should show array
